### ISSUE TITLE
_AnimateGradientState#4d0bb(tickers: tracking 1 ticker) was disposed with an active Ticker.

### ISSUE THREAD

**Issue by SpirikleOfficial** [Vikaskumar75/Animated-Gradient#2]
I'm getting error when navigating from one page to another while using animated gradient.
here is my error log:
======== Exception caught by widgets library =======================================================
The following assertion was thrown while finalizing the widget tree:
_AnimateGradientState#37126(tickers: tracking 1 ticker) was disposed with an active Ticker.

_AnimateGradientState created a Ticker via its TickerProviderStateMixin, but at the time dispose() was called on the mixin, that Ticker was still active. All Tickers must be disposed before calling super.dispose().

Tickers used by AnimationControllers should be disposed by calling dispose() on the AnimationController itself. Otherwise, the ticker will leak.

The offending ticker was: _WidgetTicker(created by _AnimateGradientState#37126)
The stack trace when the _WidgetTicker was actually created was:
#0      new Ticker.<anonymous closure> (package:flutter/src/scheduler/ticker.dart:71:40)
#1      new Ticker (package:flutter/src/scheduler/ticker.dart:73:6)
#2      new _WidgetTicker (package:flutter/src/widgets/ticker_provider.dart)
#3      TickerProviderStateMixin.createTicker (package:flutter/src/widgets/ticker_provider.dart:295:34)
#4      new AnimationController (package:flutter/src/animation/animation_controller.dart:250:21)
#5      _AnimateGradientState.initState (package:animate_gradient/animate_gradient_widget.dart:92:10)
#6      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5015:57)
#7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (25 frames)
#32     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#33     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#34     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (387 frames)
#421    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#422    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#423    Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#424    RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5964:32)
#425    MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#426    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#427    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#428    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#429    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#430    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#431    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#432    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#433    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#434    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#435    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#436    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#437    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#438    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#439    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:107:11)
#440    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#441    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#442    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#443    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#444    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#445    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#446    StatefulElement.update (package:flutter/src/widgets/framework.dart:5082:5)
#447    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#448    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#449    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#450    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#451    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#452    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#453    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#454    ProxyElement.update (package:flutter/src/widgets/framework.dart:5228:5)
#455    Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#456    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#457    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#458    Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#459    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#460    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#461    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#462    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#463    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#464    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#465    _invoke (dart:ui/hooks.dart:148:13)
#466    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#467    _drawFrame (dart:ui/hooks.dart:115:31)

When the exception was thrown, this was the stack: 
#0      TickerProviderStateMixin.dispose.<anonymous closure> (package:flutter/src/widgets/ticker_provider.dart:342:13)
#1      TickerProviderStateMixin.dispose (package:flutter/src/widgets/ticker_provider.dart:360:6)
#2      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:5105:11)
#3      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1917:13)
#4      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#8      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#9      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#10     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#12     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#13     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#14     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#15     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#16     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#17     MultiChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6398:16)
#18     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#19     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#20     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#21     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#22     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#23     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#24     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#25     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#26     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#27     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#28     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#29     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#30     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#31     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#32     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#33     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#34     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#35     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#36     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#37     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#38     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#39     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#40     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#41     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#42     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#43     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#44     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#45     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#46     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#47     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#48     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#49     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#50     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#51     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#52     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#53     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#54     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#55     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#56     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#57     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#58     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#59     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#60     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#61     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#62     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#63     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#64     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#65     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#66     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#67     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#68     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#69     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#70     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#71     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#72     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#73     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#74     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#75     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#76     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#77     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#78     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#79     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#80     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#81     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#82     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#83     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#84     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#85     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#86     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#87     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#88     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#89     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#90     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#91     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#92     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#93     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#94     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#95     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#96     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#97     _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#98     SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#99     _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#100    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#101    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#102    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#103    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#104    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#105    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#106    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#107    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#108    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#109    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#110    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#111    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#112    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#113    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#114    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#115    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#116    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#117    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#118    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#119    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#120    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#121    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#122    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#123    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#124    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#125    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#126    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#127    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#128    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#129    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#130    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#131    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#132    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#133    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#134    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#135    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#136    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#137    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#138    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#139    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#140    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#141    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#142    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#143    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#144    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#145    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#146    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#147    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#148    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#149    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#150    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#151    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#152    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#153    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#154    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#155    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#156    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#157    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#158    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#159    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#160    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#161    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#162    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#163    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#164    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#165    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#166    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#167    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#168    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#169    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#170    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#171    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#172    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#173    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#174    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#175    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#176    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#177    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#178    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#179    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#180    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#181    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#182    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#183    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#184    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#185    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#186    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#187    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#188    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#189    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#190    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#191    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#192    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#193    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#194    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#195    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#196    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#197    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#198    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#199    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#200    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#201    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#202    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#203    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#204    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#205    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#206    SingleChildRenderObjectElement.visitChildren (package:flutter/src/widgets/framework.dart:6286:14)
#207    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#208    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#209    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#210    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#211    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#212    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#213    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#214    _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1915:7)
#215    ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:4931:14)
#216    _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1913:13)
#217    ListIterable.forEach (dart:_internal/iterable.dart:39:13)
#218    _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:1926:25)
#219    BuildOwner.lockState (package:flutter/src/widgets/framework.dart:2523:15)
#220    BuildOwner.finalizeTree (package:flutter/src/widgets/framework.dart:2947:7)
#221    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:885:19)
#222    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#223    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#224    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#225    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#226    _invoke (dart:ui/hooks.dart:148:13)
#227    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#228    _drawFrame (dart:ui/hooks.dart:115:31)
====================================================================================================

**Comment by hareendranmg** [comment]
> _drawFrame (dart:ui/platform_dispatcher.dart:318:5)

Any update?

**Comment by NicolasLaube** [comment]
Hi, I tried this and it worked for me:

Extend your class by `TickerProviderStateMixin`
Create a controller
Add controller to you AnimateController

Here is what it should look like:
```
class _StateCardSideFront extends State<CardSideFront> with TickerProviderStateMixin {

AnimationController? _controller = null;

  @override
  void initState() {
    super.initState();
    _controller = AnimationController(vsync: this);
  }

  @override
  void dispose() {
    _controller?.dispose();
    super.dispose();
  }
```

**Comment by vig31** [comment]
Hey guys as @NicolasLaube  told i done the same it worked me too. But this a problem within the package as controller is properly disposed i checked with the code inside the package in my cache it didn't had any dispose function in it but in latest code in git had it. I suppose reselase need to be made.

For time being you can do like this :

```
import 'package:animate_gradient/animate_gradient.dart';
import 'package:flutter/material.dart';

class HomeScreen extends StatefulWidget {
  const HomeScreen({Key? key}) : super(key: key);

  @override
  State<HomeScreen> createState() => _HomeScreenState();
}

class _HomeScreenState extends State<HomeScreen> with TickerProviderStateMixin {
  //Create a animation controller.
  late final AnimationController animationControllerForGradient;
  @override
  void initState() {
    super.initState();
    // Assign the controller 
    animationControllerForGradient = (AnimationController(
      vsync: this,
      duration: const Duration(
        milliseconds: 2500, //duration you need
      ),
    )..repeat(reverse: true //false for restarting from the begining
));
  }

  @override
  void dispose() {
    animationControllerForGradient.dispose(); //dispose the contrller
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: AnimateGradient(
        // pass the cotroller to the controller prop.
        controller: animationControllerForGradient,
        primaryColors: const [
          Colors.pink,
          Colors.pinkAccent,
          Colors.white,
        ],
        secondaryColors: const [
          Colors.white,
          Colors.blueAccent,
          Colors.blue,
        ],
        child: const Center(
          child: Text('HomeScreen'),
        ),
      ),
    );
  }
}
```

**Comment by Vikaskumar75** [comment]
Thanks for the wait.
Please upgrade to the latest version.

Closing the issue
