### ISSUE TITLE
Change Alignment to AlignmentGeometry

### ISSUE THREAD

**Issue by pdenert** [Vikaskumar75/Animated-Gradient#3]
Although in the readme the align parameter are described as AlignmentGeometry?, they're for real are just Alignment. This makes it impossible to use this package in applications that support RTL languages.

**Comment by Vikaskumar75** [comment]
Great news, @pdenert 

We've released a new version of animate_gradient that should resolve all the issues you've reported. 
Thanks for your patience and valuable suggestion. 

Happy coding! 🎉🚀
