### ISSUE TITLE
when we want make check to change Colors of primary and secondary on change app status the colors doesnot changes

### ISSUE THREAD

**Issue by mohamedshalaby22** [Vikaskumar75/Animated-Gradient#5]

**Comment by pnilkanth12** [comment]
Hi @mohamedshalaby22 
I have no idea have you found or not to change color. if you found then it's great

I have same requirements to change gradient color on button click but it's not changeable so I read those code I notice that we passed primary color is set in initstate so it's not change on button click or setState 
so we need to make one thing is 

we need to just copy initState() code and make one method didUpdateWidget() in paste in this method

so this method call every time when state change

it's single file code you can update or make new file in your project and you can also update on this

For reference File name is: animated_gradient_widget.dart

feel free to reach out if have any doubt.

I hope my response was beneficial! 

Best of Luck 👍

Thanks a million to Author @Vikaskumar75 to make a beautiful package. 👍

**Comment by Vikaskumar75** [comment]
Great news, @mohamedshalaby22, and @pnilkanth12

We've released a new version of animate_gradient that should resolve all the issues you've reported. Thanks for your patience and valuable feedback. 

Happy coding! 🎉🚀
